cabal-version: 3.0
name: gravensteiner
version: 0.1.0.0
synopsis: Bayesian identification of apple cultivars
description:
  A Bayesian model that identifies an apple cultivar from observed
  properties such as its colour proportions.

license: MIT
license-file: LICENSE
author: Manuel Bärenz
maintainer: programming@manuelbaerenz.de
category: Statistics
build-type: Simple
extra-doc-files: CHANGELOG.md
tested-with: ghc ==9.6.7 || ==9.8.4 || ==9.10.3 || ==9.12.4

common warnings
  ghc-options: -Wall
  build-depends:
    barbies,
    base >=4.18 && <4.22,
    containers,
    delayed-sampling,
    dimensional,
    indexed-traversable,
    log-domain,
    math-functions ^>=0.3,
    monad-bayes ^>=1.3,
    text,
    time,
    uuid,

  default-extensions:
    DerivingStrategies

library
  import: warnings
  exposed-modules: Gravensteiner.Model
  hs-source-dirs: src
  default-language: GHC2021

executable gravensteiner
  import: warnings
  main-is: Main.hs
  build-depends: gravensteiner
  hs-source-dirs: app
  default-language: GHC2021
